# -*- coding: utf-8 -*-
"""Streamlit Dashboard App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgRsh8QBetmJitP45-Xy43WGMK5fju-o
"""

import streamlit as st
import streamlit.components.v1 as components
import os

# --- 1. SETUP & CONFIGURATION ---

st.set_page_config(layout="wide")

# This CSS ensures the Streamlit environment adopts the app's dark theme
st.markdown("""
<style>
/* Adjust Streamlit's main content area to match the app's dark theme */
.main {
    background-color: #0B132B;
    color: #E0E0E0;
    font-family: 'Inter', sans-serif;
}
/* Adjust the sidebar color to match the aesthetic */
.css-1d391gc { /* This class is often used for the main content background */
    background-color: #0B132B;
}
/* Ensure the entire app uses the correct font */
html, body {
    font-family: 'Inter', sans-serif;
}
</style>
""", unsafe_allow_html=True)


# --- 2. LOAD HTML PAYLOAD ---

# Read the content of the HTML payload file
# NOTE: This assumes 'talata_dashboard_payload.html' is in the same directory
# on the Streamlit Cloud server.
html_file_path = "talata_dashboard_payload.html"
html_payload = ""

try:
    with open(html_file_path, "r", encoding="utf-8") as f:
        html_payload = f.read()
except FileNotFoundError:
    st.error(f"Error: The HTML payload file '{html_file_path}' was not found. Please ensure it is in the same directory.")
    # Stop execution if file is missing
    st.stop()


# --- 3. STREAMLIT APPLICATION WRAPPER ---

st.title("Talata Operational Dashboard")
st.markdown("---")

# The main content area in Streamlit is where the HTML dashboard is injected.
# We set a large height to ensure the dashboard fits without internal scrolling.
components.html(
    html_payload,
    height=1500,
    scrolling=True
)